name: CI

on:
  pull_request:

jobs:
  build:
    if: github.event.repository.fork == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run build
        run: echo "Running build on non-forked repo"
