name: test

on:
  push

env:
  HAHA: ${{ vars.PUBLIC_ENV }}
jobs:
  test:
    # if: ${{ vars.PUBLIC_ENV  == 'public' }}
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          tag=$(gh release list --repo SiliconLabsSoftware/peripheral-examples-wiseconnect-sdk --json tagName --jq '.[0].tagName')
          echo "Processing release: $tag"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}     
