name: test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: test
        run: |
          if [ ${{ vars.TEST_ENV }} == private ]; then
          echo "hahaha"
          fi
          
          echo ${{ vars.PUBLIC_ENV }}
